tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "rigellute/tap"
brew "autojump"
brew "bandwhich"
brew "broot"
brew "cairo"
brew "coreutils"
brew "croc"
brew "curl"
brew "gnutls"
brew "ffmpeg"
brew "findutils"
brew "fnm"
brew "fzf"
brew "gawk"
brew "git"
brew "git-flow"
brew "git-lfs"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "go"
brew "gradle"
brew "grep"
brew "hadolint"
brew "hstr"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "libpq"
brew "mas"
brew "moreutils"
brew "neofetch"
brew "nmap"
brew "rustup-init"
brew "spotify-tui"
brew "spotifyd"
brew "sqlmap"
brew "tldr"
brew "tmux"
brew "tokei"
brew "wget"
brew "wifi-password"
cask "alacritty"
cask "anaconda"
cask "authy"
cask "binance"
cask "cheatsheet"
cask "contexts"
cask "dashlane"
cask "discord"
cask "figma"
cask "firefox-developer-edition"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "hazeover"
cask "hookshot"
cask "iina"
cask "imageoptim"
cask "insomnia"
cask "intellij-idea"
cask "keepingyouawake"
cask "keka"
cask "keycastr"
cask "lulu"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "mos"
cask "notion"
cask "openkey"
cask "opera"
cask "pock"
cask "postman"
cask "proxyman"
cask "rar"
cask "raycast"
cask "signal"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "teamviewer"
cask "telegram"
cask "textmate"
cask "tor-browser"
cask "tower"
cask "typora"
cask "visual-studio-code"
cask "zalo"
mas "AdGuard for Safari", id: 1440147259
mas "AwesomeScreenshot", id: 1531282066
mas "GoodNotes", id: 1444383602
mas "Grammarly for Safari", id: 1462114288
mas "ImageFinder for Safari", id: 1514863337
mas "LINE", id: 539883307
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "OneTab", id: 1540160809
mas "PiPer", id: 1421915518
mas "RunCat", id: 1429033973
mas "Shazam", id: 897118787
mas "SimplyJSON", id: 1495193038
mas "Spark", id: 1176895641
mas "Tab Suspender", id: 1495356253
mas "Wappalyzer", id: 1520333300
mas "Xcode", id: 497799835
