[tools]
node = "latest"
bun = "latest"
deno = "latest"
go = "latest"
java = "zulu"
ruby = "latest"
cargo-binstall = "latest"
slsa-verifier = "latest"
cosign = "latest"
python = "latest"
uv = "latest"
"cargo:cargo-cache" = "latest"
zig = "latest"
rust = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
